export const CATALOGO_EJERCICIOS = [
  // Pecho
  { name: 'Press banca con barra', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press banca con mancuernas', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press inclinado con barra', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press inclinado con mancuernas', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press declinado', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Aperturas con mancuernas', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Cruce de poleas', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Flexiones de brazos', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press en máquina', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Pec deck (contractora)', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Fondos en paralelas (pecho)', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press banca agarre cerrado', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Pullover con mancuerna', muscleGroup: 'pecho', type: 'peso_reps' },
  { name: 'Press banca con banda elástica', muscleGroup: 'pecho', type: 'peso_reps' },

  // Espalda
  { name: 'Dominadas', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Dominadas agarre supino', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Jalón al pecho', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Jalón al pecho agarre cerrado', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Remo con barra', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Remo con mancuerna a un brazo', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Remo en polea sentado', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Remo en máquina', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Peso muerto convencional', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Pull-over en polea', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Remo Pendlay', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Hiperextensiones lumbares', muscleGroup: 'espalda', type: 'peso_reps' },
  { name: 'Encogimientos de hombros (trapecio)', muscleGroup: 'espalda', type: 'peso_reps' },

  // Cuádriceps
  { name: 'Sentadilla con barra', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Sentadilla frontal', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Sentadilla goblet', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Sentadilla búlgara', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Prensa de piernas', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Zancadas caminando', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Zancadas estáticas', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Extensión de cuádriceps en máquina', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Sentadilla hack', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Step up al cajón', muscleGroup: 'cuadriceps', type: 'peso_reps' },
  { name: 'Sentadilla sumo', muscleGroup: 'cuadriceps', type: 'peso_reps' },

  // Isquiotibiales/Glúteos
  { name: 'Peso muerto rumano', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Curl femoral tumbado', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Curl femoral sentado', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Hip thrust', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Puente de glúteos', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Patada de glúteo en polea', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Buenos días (good morning)', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },
  { name: 'Abducción de cadera en máquina', muscleGroup: 'isquios_gluteos', type: 'peso_reps' },

  // Hombros
  { name: 'Press militar con barra', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Press militar con mancuernas', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Press Arnold', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Elevaciones laterales con mancuernas', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Elevaciones laterales en polea', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Elevaciones frontales', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Pájaros (deltoide posterior)', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Face pull', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Press tras nuca', muscleGroup: 'hombros', type: 'peso_reps' },
  { name: 'Encogimientos con mancuernas', muscleGroup: 'hombros', type: 'peso_reps' },

  // Bíceps
  { name: 'Curl con barra recta', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl con barra Z', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl con mancuernas alternado', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl martillo', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl concentrado', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl en banco Scott', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl en polea baja', muscleGroup: 'biceps', type: 'peso_reps' },
  { name: 'Curl 21s', muscleGroup: 'biceps', type: 'peso_reps' },

  // Tríceps
  { name: 'Press francés con barra', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Press francés con mancuerna', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Extensión de tríceps en polea con cuerda', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Extensión de tríceps en polea con barra', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Fondos en paralelas', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Press cerrado en banca', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Patada de tríceps con mancuerna', muscleGroup: 'triceps', type: 'peso_reps' },
  { name: 'Extensión de tríceps sobre la cabeza', muscleGroup: 'triceps', type: 'peso_reps' },

  // Core
  { name: 'Plancha', muscleGroup: 'core', type: 'tiempo' },
  { name: 'Plancha lateral', muscleGroup: 'core', type: 'tiempo' },
  { name: 'Abdominales crunch', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Abdominales en polea arrodillado', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Elevación de piernas colgado', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Elevación de piernas en banco', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Russian twist', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Rueda abdominal', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Mountain climbers', muscleGroup: 'core', type: 'peso_reps' },
  { name: 'Bicicleta abdominal', muscleGroup: 'core', type: 'peso_reps' },

  // Cardio
  { name: 'Correr en cinta', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Bicicleta fija', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Elíptica', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Remo (máquina de cardio)', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Salto de cuerda', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Escaladora (stair climber)', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Sprint', muscleGroup: 'cardio', type: 'tiempo' },
  { name: 'Burpees', muscleGroup: 'cardio', type: 'peso_reps' },
];
